### ISSUE TITLE
Cannot contact daemon, are you sure it is running?

### ISSUE THREAD

**Issue by dan-cristian** [fatso83/hubic-init-script#5]
I have installed your script and I get the following message on /etc/init.d/hubic start

/etc/init.d/hubic start
Starting hubiCCannot contact daemon, are you sure it is running?
 failed!
login failed ... failed!

I have installed all hubic prerequisites, including dbus-x11:

mono -V
Mono JIT compiler version 2.10.8.1 (Debian 2.10.8.1-8+deb7u1)
Copyright (C) 2002-2011 Novell, Inc, Xamarin, Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            Included Boehm (with typed GC and Parallel Mark)

hubiC - Keep your files synchronized - version 2.1.0.53
Copyright (C) 2012-2013 OVH SAS. All rights reserved.
Environment:
        OS: Unix 3.2.0.4
        .net framework: 4.0.30319.1
        Mono runtime: 2.10.8.1 (Debian 2.10.8.1-8+deb7u1)

**Comment by fatso83** [comment]
I am guessing this actually is not related to the script. If you can get it working without the script, using the instructions on the hubiC forums, then I am guessing this should work too.

I am also experiencing problems, and I am guessing they are the same (as I get this when running standalone), but the actual error messages are hidden in the logs somewhere when using the latest Ubuntu release:

```
$ sudo /etc/init.d/hubic start
[....] Starting hubic (via systemctl): hubic.serviceJob for hubic.service failed. See "systemctl status hubic.service" and "journalctl -xe" for details.
 failed!

$ systemctl  status hubic.service
● hubic.service - LSB: starts the hubiC synchronization client
   Loaded: loaded (/etc/init.d/hubic)
   Active: failed (Result: exit-code) since Wed 2015-04-29 15:32:58 CEST; 3s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 2581 ExecStart=/etc/init.d/hubic start (code=exited, status=3)
```

**Comment by fatso83** [comment]
@dan-cristian I don't think this script works with hubiC version 2. 

```
$ sudo -s -u hubic
[sudo] password for carl-erik:
export DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-eCbHClvbsM,guid=304113e59e73ede710bc4dff5547529a

hubic@timbuktu:~$ hubic main-loop --verbose
Command failed: An exception was thrown by the type initializer for Ovh.Hubic.Sync.Library.Interface.Constant.Miscellaneous.

hubic@timbuktu:/tmp$ hubic login myuser@gmail.com
Password
Command failed: org.freedesktop.DBus.Error.Spawn.ChildExited: Process com.hubiC exited with status 2.
```

Seems like there is some kind of problem relating to the hubic user. Maybe it needs a home directory? I can get hubic to work manually, without this script.

**Comment by leizh** [comment]
@fatso83 Which version do you use ?

Since the 0.3, the service runs as a specific user and a specific home directory (/var/run/hubic). I use it successfully with the version 2.1.53 of the client.

**Comment by fatso83** [comment]
2.1.0.53, the latest version. Using the .deb package with Ubuntu 15.04. This Ubuntu version uses a new service manager to start and stop the services. Maybe that's what's causing it?

**Comment by fatso83** [comment]
Now I have tested a bit, got it working, but also found several problems with it. My conclusion is that it is lacking some functionality before it can be used by most people, and that you probably have just used it for synchronization, not backup?

# Problems with the current version

I just list the problems here, but I can help you out with push requests if you accept contributions.

## Home directory is non-persistent

The /var/run directory is symlinked to /run, which is a tmpfs file system on Ubuntu. That means the directory is cleared on each boot. All config files for the hubic user are therefore removed at each boot, including caches to speed up indexing of large backup directories and cached login credentials.

To get it working I needed to re-create the /var/run/hubic directory with the right permissions at each boot, but this is a stupid hack. A better directory should be chosen, like `/var/lib/hubic` or `/home/hubic`.

## Not possible to do backups

Backup info is stored in the home directory under .config and .mono, and when this info is present, the backups are not attached to the local file system, and this has to be manually fixed. But as the home directory is deleted on each boot, this info is lost, and the work needs to be redone.

```
├── .config
│   ├── autostart
│   │   └── hubic.desktop
│   ├── hubiC
│   │   ├── application.log
│   │   ├── cache-294435b0831312525abbba3765a383af-backup-06f173c1367d38d42139280990a8b2b8.db
│   │   ├── cache-294435b0831312525abbba3765a383af-backup-06f173c1367d38d42139280990a8b2b8.db-journal
│   │   ├── cache-294435b0831312525abbba3765a383af-backup-b18e8acbadab35178cd32d8d95c55c41.db
│   │   ├── cache-294435b0831312525abbba3765a383af-backup-d06d996e7373254392e344459675ca24.db
│   │   ├── cache-294435b0831312525abbba3765a383af-backup-d06d996e7373254392e344459675ca24.db-journal
│   │   ├── hubiC.db
│   │   └── hubiC.db-journal
│   └── .mono
│       ├── certs
│       │   └── Trust
│       │       ├── ski-607B661A450D97CA89502F7D04CD34A8FFFCFD4B.cer
│       │       └── ski-9BE20757671C1EC06A06DE59B49A2DDFDC19862E.cer
│       └── keypairs
│           └── [1][98f3a7e3-0d6e-f432-8a18-e1144b53633f][-1].xml
└── .mono
    └── registry
        ├── CurrentUser
        │   └── software
        │       └── ovh
        │           └── hubic-sync
        │               ├── organizationdefaults
        │               │   └── values.xml
        │               └── values.xml
        └── last-btime
```

## Enforcing sync directory, but sync is optional

I do not have a sync directory, using hubic only for backups of my file server, but the script explicitly forces me to name one, so I set it to /tmp/foobar. Not strictly needed.

**Comment by fatso83** [comment]
I have tried fixing some of the problems in [my fork](/fatso83/hubic-init-script), including updating the README with notes on how to debug problems and adding backups.

**Comment by leizh** [comment]
Thanks for this report.
I test only on Debian and I use it for backup (but not from the home directory).
I am on a bike trip for 4 months, so I cannot test and merge your fork at this moment. Sorry.

**Comment by fatso83** [comment]
good to know! Bon voyage :-)

**Comment by fatso83** [comment]
These changes have been incorporated into the repo. Closing as fixed.
