### ISSUE TITLE
Problem with pause and resume

### ISSUE THREAD

**Issue by emanuelebruno** [fatso83/hubic-init-script#7]
Hi, I need from crontab to pause and resume during backup procedure... but I have met a problem:
the pause command works correctly... the resume doesn't work.
my environment is proxmox 3.4, backup procedure start at midnight and end after 2 hours.
In crontab I have written:
0 0 \* \* 0 /etc/init.d/hubic pause
0 5 \* \* 0 /etc/init.d/hubic resume
Thank you for your reply.

**Comment by fatso83** [comment]
Hi, again. Did you get anywhere with this? Does it work when doing this manually?

**Comment by fatso83** [comment]
Closing due to lack of response.
