### ISSUE TITLE
proxmox issue

### ISSUE THREAD

**Issue by emanuelebruno** [fatso83/hubic-init-script#8]
Hi,
I hope that you can help me. Your script doesn't work in Proxmox 4.2 environment. I have found another script (https://forums.hubic.com/showthread.php?2595-Debian-7-HubiC-cant-start-login) that seems to work... but I prefer your job...

Waiting for your answer.
Emanuele Bruno.

**Comment by fatso83** [comment]
Hi, Emanuel. I just took over maintainership of this repo. Do you have any more info than "it doesn't work"? Try for instance the section on [debugging errors](https://github.com/fatso83/hubic-init-script#debugging-errors). Tell me if you get any wizer and if not, give some output from the commands listed.

**Comment by fatso83** [comment]
Closing this due to missing response.
